# Building
FROM golang:1.17-alpine AS builder
RUN apk --update --no-cache add git make
WORKDIR /app

COPY ./ ./

# Deps && Build
RUN make deps
RUN make build


# Runtime 
FROM scratch
COPY --from=builder /app/build/go-calc /go-calc
ENTRYPOINT ["/go-calc"]
