package:
  name: hello-server
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - go

pipeline:
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -installsuffix 'static' -o "${{targets.destdir}}/build/go-calc" .
